
version: '2.1'
services:
  base-gitlab-runner:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - IMAGE_ARG_APT_MIRROR=${IMAGE_ARG_APT_MIRROR:-mirrors.163.com}
      - IMAGE_ARG_GITLAB_RUNNER_MIRROR=${IMAGE_ARG_GITLAB_RUNNER_MIRROR:-https://mirrors.tuna.tsinghua.edu.cn}

      - IMAGE_ARG_ENCODING=${IMAGE_ARG_ENCODING:-UTF-8}
      - IMAGE_ARG_JAVA_OPTS=${IMAGE_ARG_JAVA_OPTS}
      - IMAGE_ARG_LANGUAGE=${IMAGE_ARG_LANGUAGE:-en}
      - IMAGE_ARG_LOCALE=${IMAGE_ARG_LOCALE:-en_US}
      - IMAGE_ARG_REGION=${IMAGE_ARG_REGION:-US}
      #- IMAGE_ARG_TZ=${IMAGE_ARG_TZ:-UTC+8:00}
      - IMAGE_ARG_TZ_AREA=${IMAGE_ARG_TZ_AREA:-Etc}
      - IMAGE_ARG_TZ_ZONE=${IMAGE_ARG_TZ_ZONE:-UTC}

      - IMAGE_ARG_USER=${IMAGE_ARG_USER:-ubuntu}
      - IMAGE_ARG_VERSION=${IMAGE_ARG_VERSION:-11.3.1}
    environment:
    # Do not set token here. Let users set this in gitlab project -> settings -> CI/DI pipelines
    - CI_INFRA_OPT_GIT_AUTH_TOKEN=${CI_INFRA_OPT_GIT_AUTH_TOKEN:-your_CI_INFRA_OPT_GIT_AUTH_TOKEN}
    image: ${IMAGE_PREFIX:-cirepo}/${IMAGE_NAME:-gitlab-runner}:${IMAGE_TAG:-11.3.1-en_US.UTF-8_Etc.UTC-bionic}
    restart: always
